
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: planner
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: donotcrackplease
    ports:
      - "5432:5432"
  api: 
    build: .
    environment:
      POSTGRES_CONN_STR: "postgres://admin:donotcrackplease@database/planner?sslmode=disable"
    depends_on:
      - database
    ports:
      - "8080:8080"
